name: Publish

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "vite-plugin*" # # Push events to matching vite-plugin*, i.e. vite-plugin-sfce@1.0.0

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Publish and Release tag
    if: github.repository == 'sotnikovse/vitempl'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get pkgName for tag
        id: tag
        run: |
          # matching v2.0.0 / v2.0.0-beta.8 etc
          if [[ $GITHUB_REF_NAME =~ ^v\d.+ ]]; then
            pkgName="vitempl"
          else
            # `%@*` truncates @ and version number from the right side.
            # https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
            pkgName=${GITHUB_REF_NAME%@*}
          fi
          echo "pkgName=$pkgName" >> $GITHUB_OUTPUT
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build and Publish to npm
        run: npm publish --workspace="./packages/${{ steps.tag.outputs.pkgName }}" --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release for Tag
        id: release_tag
        uses: yyx990803/release-tag@8cccf7c5aa332d71d222df46677f70f77a8d2dc0 # v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/sotnikovse/vitempl/blob/${{ github.ref_name }}/packages/${{ steps.tag.outputs.pkgName }}/CHANGELOG.md) for details.
